# Generated by Django 4.2.4 on 2023-10-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
