# Generated by Django 4.2.4 on 2023-10-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='status_of_order',
        ),
    ]
