# Generated by Django 4.2.4 on 2023-10-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_rename_status_order_status_of_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status_of_order',
            new_name='processing_if_false',
        ),
    ]
