# Generated by Django 4.2.4 on 2023-10-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createorder',
            name='user',
        ),
    ]
