# Generated by Django 4.2.4 on 2023-10-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_products_slug'),
        ('purchase', '0003_createorder_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='home.products')),
            ],
        ),
        migrations.AlterField(
            model_name='createorder',
            name='items',
            field=models.ManyToManyField(to='purchase.item'),
        ),
    ]
