# Generated by Django 4.2.4 on 2023-10-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_item_alter_createorder_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product',
            new_name='products',
        ),
    ]
