# Generated by Django 4.2.4 on 2023-10-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_rename_product_item_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createorder',
            name='items',
            field=models.ManyToManyField(to='purchase.cartitem'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
