# Generated by Django 4.2.4 on 2023-10-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_createorder_items_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='createorder',
            name='items',
        ),
    ]
