# Generated by Django 4.2.4 on 2023-10-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_products_slug'),
        ('purchase', '0007_remove_cart_items_remove_createorder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='purchase.CartItem', to='home.products'),
        ),
    ]
