# Generated by Django 4.2.4 on 2023-10-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_createorder_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='createorder',
            name='items',
        ),
    ]
