# Generated by Django 4.2.4 on 2023-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_remove_cart_items_remove_createorder_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='createorder',
            name='cartItem',
            field=models.ManyToManyField(to='purchase.cartitem'),
        ),
    ]
