# Generated by Django 4.2.4 on 2023-10-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_createorder_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createorder',
            name='cartItem',
        ),
    ]
